configversion: 5
#========================================
#             Custom Structures    
#========================================
#Wiki: https://github.com/ryandw11/CustomStructures/wiki

#Log extra information in console when generating structures
debug: false

#bstats is where data is sent. https://bstats.org/plugin/bukkit/CustomStructures .
#Here is some more information on it like what it collects and how to disable it all togeather and not just for this plugin.
# https://bstats.org/getting-started
bstats: true

#Allow Plugins to delete structures at will.
allowDeletion: true

Structures:
    - demo